version: "3.7"

services:
  mysqldb1:
   container_name: mysqldb1
   image: mysql:5.6
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tpachato
    MYSQL_ROOT: root
    MYSQL_PASSWORD: root
    MYSQL_HOST: mysqldb1
   ports:
    - 3306:3306    

   healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
   volumes:
     - /home/mysql/data:/var/lib/mysql --user 1000

  spring_app:
   image: youssefba97/produit1:latest
   container_name: produit1
   ports:
    - 8089:8089
   environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb1:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tpachato
   restart: on-failure
   links:
      - mysqldb1
